// Generated by Wrangler by running `wrangler types --experimental-include-runtime`

interface Env {
	TWITTER_API_KEY: string
	TWITTER_API_SECRET: string
	TWITTER_ACCESS_TOKEN: string
	TWITTER_ACCESS_TOKEN_SECRET: string
}
